### ISSUE TITLE
An incompatible version of pytorch provided in mimic_env.yaml

### ISSUE THREAD

**Issue by Thomaswbt** [BarryRun/COGNet#3]
Hi authors!
After I initialized the conda environment with the provided file **mimic_env.yaml**, I found that I cannot run the code because the class of nn.TransformerEncoderLayer for Pytorch versions under 1.9.0 do not have the **batch_first** parameter, while running the provided mimic_env.yaml file would automatically install Pytorch version 1.7.1. I successfully trained the model after I upgraded Pytorch to 1.10.0. Hence, I believe it would be great if you could modify the mimic_env.yaml file. Thanks a lot in advance!

**Comment by BarryRun** [comment]
I will fix it, thank you for correcting the mistake!
